# Generated by Django 5.1 on 2024-08-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('favorite_subject', models.CharField(max_length=100)),
                ('disliked_subject', models.CharField(max_length=100)),
                ('preferred_major', models.CharField(max_length=100)),
                ('exam_score', models.IntegerField()),
            ],
        ),
    ]
