# Generated by Django 5.1 on 2024-08-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('academic_strengths', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=5)),
                ('aspirations', models.CharField(max_length=50)),
                ('learning_preferences', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
